Add support for 'y' (yes) for confirmation
cyberark/conjur-api-python3 pull request #219
Opened 2021-02-28 07:25 UTC by sigalsax

We previously only supported 'yes' and 'YES' for confirmation. Now, 'y' and 'Y' are supported.

### What does this PR do?
- _What's changed? Why were these changes made?_
- _How should the reviewer approach this PR, especially if manual tests are required?_
- _Are there relevant screenshots you can add to the PR description?_

### What ticket does this PR close?
Resolves #[relevant GitHub issues, eg 76]

### Checklists

#### Change log
- [ ] The CHANGELOG has been updated, or
- [ ] This PR does not include user-facing changes and doesn't require a CHANGELOG update

#### Test coverage
- [ ] This PR includes new unit and integration tests to go with the code changes, or
- [ ] The changes in this PR do not require tests

#### Documentation
- [ ] Docs (e.g. `README`s) were updated in this PR, and/or there is a follow-on issue to update docs, or
- [ ] This PR does not require updating any documentation

2021-02-28 16:19 UTC, tzheleznyak commented on conjur/controller/init_controller.py
> +        if force_overwrite != '' and force_overwrite.lower() != 'yes' and force_overwrite.lower() != 'y' :
Do it using a list of possible options.
```suggestion
        if force_overwrite != '' and force_overwrite.lower() in APPROVAL_WORDS:
```

2021-02-28 16:20 UTC, tzheleznyak commented on test/test_integration_configurations.py
> +    test_https_conjurrc_is_created_when_user_provides_y_instead_of_yes_for_overwrite.tester=True
Should it stay here?

2021-02-28 16:20 UTC, tzheleznyak requested changes
Left some comments

2021-03-01 05:39 UTC, sigalsax commented on test/test_integration_configurations.py
> +    test_https_conjurrc_is_created_when_user_provides_y_instead_of_yes_for_overwrite.tester=True
great catch! no it shouldnt (:

2021-03-01 07:05 UTC, tzheleznyak approved these changes
LGTM

2021-03-01 07:07 UTC, merged