hostfactory TW review
cyberark/conjur-api-python3 pull request #357
Opened 2021-11-07 10:21 UTC by hzur

### Desired Outcome

All technical-writer logs reviewed

2021-11-08 13:44 UTC, shulifink requested changes
I had some questions. Let's discuss

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                          help='Allows creating hosts dynamically and manage hostfactory tokens',
```suggestion
                        help='Allow creating hosts dynamically and managing Host Factory tokens',
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          hostfactory_create_name = 'create - Create token for creating hosts ' \
```suggestion
        hostfactory_create_name = 'create - Create Host Factory token for creating hosts ' \
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          hostfactory_name = 'hostfactory - Manage hosts and tokens'
@hzur  - HF tokens? ie 
```suggestion
        hostfactory_name = 'hostfactory - Manage hosts and Host Factory tokens'
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          hostfactory_create_name = 'create - Create token for creating hosts ' \
Maybe "Generate Host Factory token... " otherwise "create "and "create" is too much "create"

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                    'with restrictions or creates a host using the Host Factory'
```suggestion
                                  'with restrictions or create a host using the Host Factory'
```

Not sure what exaclty the meaning is here. Let's discuss

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          hostfactory_create_usage = 'conjur [global options] hostfactory ' \
nothing for me to review here

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                          help='Creates a token for creating hosts or creates a host using a token',
oh boy
```suggestion
                        help='Generate a Host Factory token for creating hosts, or create a host using a Host Factory token',
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          hostfactory_revoke_name = 'revoke - Revokes a token, immediately disabling it'
```suggestion
        hostfactory_revoke_name = 'revoke - Revoke a Host Factory token and disable it immediately'
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          hostfactory_revoke_usage = 'conjur [global options] hostfactory ' \
nothing to review here

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                          help='Revokes a token, immediately disabling it',
not sure what the difference is between this and and line 98

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          hostfactory_revoke_token_name = 'token - Revokes a token, immediately disabling it'
same as above (see comment in 106)

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                          help='Revokes a token, immediately disabling it',
same as above

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                            help='(Mandatory) the Host Factory Token to revoke')
(Mandatory) Host Factory token to revoke

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                            help='Display help screen and exit')
fine

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                          'with restrictions'
Generate a Host Factory token for creating hosts with rrestrictions". (BTW, does the token have restrictions, or the host?)

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                    help='(Mandatory) The ID of the Host Factory'
```suggestion
                                  help='(Mandatory) Host Factory ID to work with'
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                    help='(Optional) the CIDR address that contains '
(Optional) CIDR containing all IP addresses that can use Host Factory token for creating hosts

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                         'of the Host Factory token.')
```suggestion
                                       'of Host Factory token')
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                    help='(Optional) The validity (in days) '
```suggestion
                                  help='(Optional) Validity (in days) '
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                    help='(Optional) The validity (in hours) '
```suggestion
                                  help='(Optional) Validity (in hours) '
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                          'of the Host Factory token.')
```suggestion
                                        'of Host Factory token')
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                    help='(Optional) The validity (in minutes) '
same as above - no :the"s and remove period on end

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                    help='Display help screen and exit')
fine

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>          name = 'host - Creates a Host using the Host Factory'
```suggestion
        name = 'host - Create host using Host Factory'
```

2021-11-08 13:44 UTC, shulifink commented on conjur/argument_parser/_hostfactory_parser.py
>                                   help='(Mandatory) Identifier of the host to be created. '
```suggestion
                                 help='(Mandatory) Identifier of host to be created '
```

2021-11-08 13:44 UTC, shulifink commented on conjur/controller/hostfactory_controller.py
>  INVALID_TOKEN_ERROR = "Cannot create a host using the Host " \
```suggestion
INVALID_TOKEN_ERROR = "Cannot create host using Host " \
```

2021-11-08 13:44 UTC, shulifink commented on conjur/controller/hostfactory_controller.py
>          logging.debug(f"Creating token for hostfactory '{create_token_data.host_factory}'...")
```suggestion
        logging.debug(f"Creating Host Factory token for '{create_token_data.host_factory}'...")
```

2021-11-08 13:44 UTC, shulifink commented on conjur/controller/hostfactory_controller.py
>          logging.debug("Successfully created token for hostfactory "
```suggestion
        logging.debug("Successfully created Host Factory token "
```

2021-11-08 13:44 UTC, shulifink commented on conjur/controller/hostfactory_controller.py
>              logging.debug("Successfully created host using hostfactory: host_id:"
token??? - Let's discuss

2021-11-08 13:44 UTC, shulifink commented on conjur/controller/hostfactory_controller.py
>          logging.debug(f'Successfully revoked token'
```suggestion
        logging.debug(f'Successfully revoked Host Factory token'
```

2021-11-09 10:35 UTC, szamir1 submitted a review, later dismissed

2021-11-11 14:01 UTC, shulifink submitted a review, later dismissed

2021-11-14 11:25 UTC, shulifink approved these changes

2021-11-14 13:15 UTC, mbenita-Cyberark approved these changes
After shuli approved and rebase has been done.
Great work Harel

2021-11-14 13:16 UTC, merged